name:  bank environment
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - seaborn
  - matplotlib
  - numpy
  - ipywidgets
  - skylearn
  - scipy
  - IPython
  - warnings
  - random
